version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directories:
      - "/compare_pdfs"
      - "/convert_source_description"  
    schedule:
      interval: daily
