name: Visualize repo with diagram

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  visualize_repo:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'webern-unibas-ch'
    permissions:
      contents: write
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Update diagram
        uses: githubocto/repo-visualizer@a999615bdab757559bf94bda1fe6eef232765f85 # v0.9.1
        with:
          excluded_paths: ".github"
