name: Visualize repo with diagram

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  visualize_repo:
    permissions:
      contents: write  # for githubocto/repo-visualizer to commit and push diagrams
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Update diagram
        uses: githubocto/repo-visualizer@a999615bdab757559bf94bda1fe6eef232765f85 # v0.9.1
        with:
          excluded_paths: ".github"
