name: Visualize repo with diagram

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  visualize_repo:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'webern-unibas-ch'
    permissions:
      contents: write
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Update diagram
        uses: githubocto/repo-visualizer@a999615bdab757559bf94bda1fe6eef232765f85 # v0.9.1
        with:
          excluded_paths: ".github"
